# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/dialogNewHardware.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogHw(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 290)
        Dialog.setMinimumSize(QtCore.QSize(340, 290))
        Dialog.setMaximumSize(QtCore.QSize(340, 290))
        Dialog.setSizeIncrement(QtCore.QSize(340, 290))
        Dialog.setBaseSize(QtCore.QSize(340, 290))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.EditDialog = QtWidgets.QLineEdit(Dialog)
        self.EditDialog.setGeometry(QtCore.QRect(73, 10, 170, 25))
        self.EditDialog.setMinimumSize(QtCore.QSize(170, 25))
        self.EditDialog.setMaximumSize(QtCore.QSize(170, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialog.setFont(font)
        self.EditDialog.setReadOnly(True)
        self.EditDialog.setObjectName("EditDialog")
        self.labelDialog = QtWidgets.QLabel(Dialog)
        self.labelDialog.setGeometry(QtCore.QRect(10, 13, 60, 20))
        self.labelDialog.setMinimumSize(QtCore.QSize(60, 20))
        self.labelDialog.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelDialog.setFont(font)
        self.labelDialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDialog.setObjectName("labelDialog")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 320, 210))
        self.tableWidget.setMinimumSize(QtCore.QSize(320, 210))
        self.tableWidget.setMaximumSize(QtCore.QSize(320, 210))
        self.tableWidget.setSizeIncrement(QtCore.QSize(320, 210))
        self.tableWidget.setBaseSize(QtCore.QSize(320, 210))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(318)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(318)
        self.btHwAdd = QtWidgets.QPushButton(Dialog)
        self.btHwAdd.setGeometry(QtCore.QRect(248, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btHwAdd.setFont(font)
        self.btHwAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btHwAdd.setText("")
        self.btHwAdd.setFlat(True)
        self.btHwAdd.setObjectName("btHwAdd")
        self.btHwDel = QtWidgets.QPushButton(Dialog)
        self.btHwDel.setGeometry(QtCore.QRect(273, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btHwDel.setFont(font)
        self.btHwDel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btHwDel.setText("")
        self.btHwDel.setFlat(True)
        self.btHwDel.setObjectName("btHwDel")
        self.btSave = QtWidgets.QPushButton(Dialog)
        self.btSave.setGeometry(QtCore.QRect(298, 10, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btSave.setFont(font)
        self.btSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSave.setText("")
        self.btSave.setFlat(True)
        self.btSave.setObjectName("btSave")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EditDialog, self.tableWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDialog.setText(_translate("Dialog", "Hardware"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Opzioni"))

