# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/dialogLic.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogLic(object):
    def setupUi(self, DialogLic):
        DialogLic.setObjectName("DialogLic")
        DialogLic.resize(730, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogLic.sizePolicy().hasHeightForWidth())
        DialogLic.setSizePolicy(sizePolicy)
        DialogLic.setMinimumSize(QtCore.QSize(730, 500))
        DialogLic.setMaximumSize(QtCore.QSize(730, 500))
        DialogLic.setSizeIncrement(QtCore.QSize(730, 500))
        DialogLic.setBaseSize(QtCore.QSize(730, 500))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        DialogLic.setFont(font)
        DialogLic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget = QtWidgets.QTableWidget(DialogLic)
        self.tableWidget.setGeometry(QtCore.QRect(10, 120, 710, 320))
        self.tableWidget.setMinimumSize(QtCore.QSize(710, 320))
        self.tableWidget.setMaximumSize(QtCore.QSize(710, 320))
        self.tableWidget.setSizeIncrement(QtCore.QSize(710, 320))
        self.tableWidget.setBaseSize(QtCore.QSize(710, 420))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(159)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(318)
        self.labelClient = QtWidgets.QLabel(DialogLic)
        self.labelClient.setGeometry(QtCore.QRect(10, 10, 60, 20))
        self.labelClient.setMinimumSize(QtCore.QSize(60, 20))
        self.labelClient.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelClient.setFont(font)
        self.labelClient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelClient.setObjectName("labelClient")
        self.lineEditClient = QtWidgets.QLineEdit(DialogLic)
        self.lineEditClient.setGeometry(QtCore.QRect(76, 10, 140, 21))
        self.lineEditClient.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditClient.setObjectName("lineEditClient")
        self.labelName = QtWidgets.QLabel(DialogLic)
        self.labelName.setGeometry(QtCore.QRect(30, 37, 60, 20))
        self.labelName.setMinimumSize(QtCore.QSize(60, 20))
        self.labelName.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelName.setObjectName("labelName")
        self.lineEditName = QtWidgets.QLineEdit(DialogLic)
        self.lineEditName.setGeometry(QtCore.QRect(76, 37, 140, 21))
        self.lineEditName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditName.setObjectName("lineEditName")
        self.labelEmail = QtWidgets.QLabel(DialogLic)
        self.labelEmail.setGeometry(QtCore.QRect(23, 63, 60, 20))
        self.labelEmail.setMinimumSize(QtCore.QSize(60, 20))
        self.labelEmail.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelEmail.setFont(font)
        self.labelEmail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelEmail.setObjectName("labelEmail")
        self.lineEditEmail = QtWidgets.QLineEdit(DialogLic)
        self.lineEditEmail.setGeometry(QtCore.QRect(76, 63, 140, 21))
        self.lineEditEmail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.comboBoxProv = QtWidgets.QComboBox(DialogLic)
        self.comboBoxProv.setGeometry(QtCore.QRect(76, 90, 140, 21))
        self.comboBoxProv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBoxProv.setObjectName("comboBoxProv")
        self.labelProv = QtWidgets.QLabel(DialogLic)
        self.labelProv.setGeometry(QtCore.QRect(4, 90, 70, 20))
        self.labelProv.setMinimumSize(QtCore.QSize(70, 20))
        self.labelProv.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelProv.setFont(font)
        self.labelProv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelProv.setObjectName("labelProv")
        self.labelQty = QtWidgets.QLabel(DialogLic)
        self.labelQty.setGeometry(QtCore.QRect(234, 10, 60, 20))
        self.labelQty.setMinimumSize(QtCore.QSize(60, 20))
        self.labelQty.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelQty.setFont(font)
        self.labelQty.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelQty.setObjectName("labelQty")
        self.lineEditQty = QtWidgets.QLineEdit(DialogLic)
        self.lineEditQty.setGeometry(QtCore.QRect(300, 10, 40, 21))
        self.lineEditQty.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditQty.setObjectName("lineEditQty")
        self.dateEditActive = QtWidgets.QDateEdit(DialogLic)
        self.dateEditActive.setGeometry(QtCore.QRect(300, 37, 110, 25))
        self.dateEditActive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEditActive.setCalendarPopup(True)
        self.dateEditActive.setObjectName("dateEditActive")
        self.labelActive = QtWidgets.QLabel(DialogLic)
        self.labelActive.setGeometry(QtCore.QRect(271, 39, 30, 20))
        self.labelActive.setMinimumSize(QtCore.QSize(30, 20))
        self.labelActive.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelActive.setFont(font)
        self.labelActive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelActive.setObjectName("labelActive")
        self.labelExpire = QtWidgets.QLabel(DialogLic)
        self.labelExpire.setGeometry(QtCore.QRect(264, 67, 30, 20))
        self.labelExpire.setMinimumSize(QtCore.QSize(30, 20))
        self.labelExpire.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelExpire.setFont(font)
        self.labelExpire.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelExpire.setObjectName("labelExpire")
        self.dateEditExpire = QtWidgets.QDateEdit(DialogLic)
        self.dateEditExpire.setGeometry(QtCore.QRect(300, 65, 110, 25))
        self.dateEditExpire.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEditExpire.setCalendarPopup(True)
        self.dateEditExpire.setObjectName("dateEditExpire")
        self.btGenerate = QtWidgets.QPushButton(DialogLic)
        self.btGenerate.setGeometry(QtCore.QRect(464, 70, 30, 26))
        self.btGenerate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btGenerate.setText("")
        self.btGenerate.setObjectName("btGenerate")
        self.btSave = QtWidgets.QPushButton(DialogLic)
        self.btSave.setGeometry(QtCore.QRect(590, 70, 30, 26))
        self.btSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSave.setText("")
        self.btSave.setObjectName("btSave")
        self.lineEditClient_2 = QtWidgets.QLineEdit(DialogLic)
        self.lineEditClient_2.setGeometry(QtCore.QRect(464, 10, 261, 21))
        self.lineEditClient_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditClient_2.setReadOnly(True)
        self.lineEditClient_2.setObjectName("lineEditClient_2")
        self.labelQty_2 = QtWidgets.QLabel(DialogLic)
        self.labelQty_2.setGeometry(QtCore.QRect(430, 10, 30, 20))
        self.labelQty_2.setMinimumSize(QtCore.QSize(30, 20))
        self.labelQty_2.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelQty_2.setFont(font)
        self.labelQty_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelQty_2.setObjectName("labelQty_2")
        self.lineEditClient_3 = QtWidgets.QLineEdit(DialogLic)
        self.lineEditClient_3.setGeometry(QtCore.QRect(464, 37, 261, 21))
        self.lineEditClient_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditClient_3.setReadOnly(True)
        self.lineEditClient_3.setObjectName("lineEditClient_3")
        self.labelQty_3 = QtWidgets.QLabel(DialogLic)
        self.labelQty_3.setGeometry(QtCore.QRect(430, 37, 30, 20))
        self.labelQty_3.setMinimumSize(QtCore.QSize(30, 20))
        self.labelQty_3.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelQty_3.setFont(font)
        self.labelQty_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelQty_3.setObjectName("labelQty_3")
        self.btDelete = QtWidgets.QPushButton(DialogLic)
        self.btDelete.setGeometry(QtCore.QRect(10, 450, 31, 26))
        self.btDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btDelete.setText("")
        self.btDelete.setObjectName("btDelete")
        self.labelGenerate = QtWidgets.QLabel(DialogLic)
        self.labelGenerate.setGeometry(QtCore.QRect(500, 73, 60, 20))
        self.labelGenerate.setMinimumSize(QtCore.QSize(60, 20))
        self.labelGenerate.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelGenerate.setFont(font)
        self.labelGenerate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelGenerate.setObjectName("labelGenerate")
        self.labelSave = QtWidgets.QLabel(DialogLic)
        self.labelSave.setGeometry(QtCore.QRect(627, 73, 60, 20))
        self.labelSave.setMinimumSize(QtCore.QSize(60, 20))
        self.labelSave.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelSave.setFont(font)
        self.labelSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelSave.setObjectName("labelSave")
        self.labelDelete = QtWidgets.QLabel(DialogLic)
        self.labelDelete.setGeometry(QtCore.QRect(45, 453, 60, 20))
        self.labelDelete.setMinimumSize(QtCore.QSize(60, 20))
        self.labelDelete.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelDelete.setFont(font)
        self.labelDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDelete.setObjectName("labelDelete")

        self.retranslateUi(DialogLic)
        QtCore.QMetaObject.connectSlotsByName(DialogLic)
        DialogLic.setTabOrder(self.lineEditClient, self.lineEditName)
        DialogLic.setTabOrder(self.lineEditName, self.lineEditEmail)
        DialogLic.setTabOrder(self.lineEditEmail, self.comboBoxProv)
        DialogLic.setTabOrder(self.comboBoxProv, self.lineEditQty)
        DialogLic.setTabOrder(self.lineEditQty, self.dateEditActive)
        DialogLic.setTabOrder(self.dateEditActive, self.dateEditExpire)
        DialogLic.setTabOrder(self.dateEditExpire, self.lineEditClient_2)
        DialogLic.setTabOrder(self.lineEditClient_2, self.lineEditClient_3)
        DialogLic.setTabOrder(self.lineEditClient_3, self.btGenerate)
        DialogLic.setTabOrder(self.btGenerate, self.btSave)
        DialogLic.setTabOrder(self.btSave, self.tableWidget)
        DialogLic.setTabOrder(self.tableWidget, self.btDelete)

    def retranslateUi(self, DialogLic):
        _translate = QtCore.QCoreApplication.translate
        DialogLic.setWindowTitle(_translate("DialogLic", "Azioni utenti"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogLic", "Client"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogLic", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogLic", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DialogLic", "Prov"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DialogLic", "Qtà"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DialogLic", "Attivo"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DialogLic", "Scade"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("DialogLic", "Req"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("DialogLic", "Lic"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("DialogLic", "Server-ID"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("DialogLic", "Active"))
        self.labelClient.setText(_translate("DialogLic", "Cliente"))
        self.labelName.setText(_translate("DialogLic", "Nome"))
        self.labelEmail.setText(_translate("DialogLic", "Email"))
        self.labelProv.setText(_translate("DialogLic", "Provincia"))
        self.labelQty.setText(_translate("DialogLic", "Quantità"))
        self.labelActive.setText(_translate("DialogLic", "Dal"))
        self.labelExpire.setText(_translate("DialogLic", "Fino"))
        self.labelQty_2.setText(_translate("DialogLic", "Req"))
        self.labelQty_3.setText(_translate("DialogLic", "Lic"))
        self.labelGenerate.setText(_translate("DialogLic", "Genera"))
        self.labelSave.setText(_translate("DialogLic", "Salva"))
        self.labelDelete.setText(_translate("DialogLic", "Elimina"))

