# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/dialogLogs.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogLogs(object):
    def setupUi(self, DialogLogs):
        DialogLogs.setObjectName("DialogLogs")
        DialogLogs.resize(730, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogLogs.sizePolicy().hasHeightForWidth())
        DialogLogs.setSizePolicy(sizePolicy)
        DialogLogs.setMinimumSize(QtCore.QSize(730, 500))
        DialogLogs.setMaximumSize(QtCore.QSize(730, 500))
        DialogLogs.setSizeIncrement(QtCore.QSize(730, 500))
        DialogLogs.setBaseSize(QtCore.QSize(730, 500))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        DialogLogs.setFont(font)
        DialogLogs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget = QtWidgets.QTableWidget(DialogLogs)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 710, 320))
        self.tableWidget.setMinimumSize(QtCore.QSize(710, 320))
        self.tableWidget.setMaximumSize(QtCore.QSize(710, 320))
        self.tableWidget.setSizeIncrement(QtCore.QSize(710, 320))
        self.tableWidget.setBaseSize(QtCore.QSize(710, 420))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(159)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(318)
        self.labelFrom = QtWidgets.QLabel(DialogLogs)
        self.labelFrom.setGeometry(QtCore.QRect(181, 6, 20, 20))
        self.labelFrom.setMinimumSize(QtCore.QSize(20, 20))
        self.labelFrom.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelFrom.setFont(font)
        self.labelFrom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelFrom.setObjectName("labelFrom")
        self.labelTo = QtWidgets.QLabel(DialogLogs)
        self.labelTo.setGeometry(QtCore.QRect(457, 7, 20, 20))
        self.labelTo.setMinimumSize(QtCore.QSize(20, 20))
        self.labelTo.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelTo.setFont(font)
        self.labelTo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelTo.setObjectName("labelTo")
        self.comboBox = QtWidgets.QComboBox(DialogLogs)
        self.comboBox.setGeometry(QtCore.QRect(3, 30, 131, 27))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.labelUsername = QtWidgets.QLabel(DialogLogs)
        self.labelUsername.setGeometry(QtCore.QRect(46, 10, 60, 20))
        self.labelUsername.setMinimumSize(QtCore.QSize(60, 20))
        self.labelUsername.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelUsername.setObjectName("labelUsername")
        self.calendarFrom = QtWidgets.QCalendarWidget(DialogLogs)
        self.calendarFrom.setGeometry(QtCore.QRect(200, 4, 251, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendarFrom.setFont(font)
        self.calendarFrom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarFrom.setGridVisible(True)
        self.calendarFrom.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarFrom.setObjectName("calendarFrom")
        self.calendarTo = QtWidgets.QCalendarWidget(DialogLogs)
        self.calendarTo.setGeometry(QtCore.QRect(470, 4, 251, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendarTo.setFont(font)
        self.calendarTo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendarTo.setGridVisible(True)
        self.calendarTo.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarTo.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarTo.setObjectName("calendarTo")
        self.btFind = QtWidgets.QPushButton(DialogLogs)
        self.btFind.setGeometry(QtCore.QRect(137, 30, 41, 27))
        self.btFind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btFind.setText("")
        self.btFind.setObjectName("btFind")

        self.retranslateUi(DialogLogs)
        QtCore.QMetaObject.connectSlotsByName(DialogLogs)

    def retranslateUi(self, DialogLogs):
        _translate = QtCore.QCoreApplication.translate
        DialogLogs.setWindowTitle(_translate("DialogLogs", "Azioni utenti"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogLogs", "Data"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogLogs", "Utente"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogLogs", "Azione"))
        self.labelFrom.setText(_translate("DialogLogs", "Da"))
        self.labelTo.setText(_translate("DialogLogs", "A"))
        self.labelUsername.setText(_translate("DialogLogs", "Utente"))

