# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/dialogNewItem.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogItem(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(340, 290))
        Dialog.setMaximumSize(QtCore.QSize(340, 290))
        Dialog.setSizeIncrement(QtCore.QSize(340, 290))
        Dialog.setBaseSize(QtCore.QSize(340, 290))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.EditDialog = QtWidgets.QLineEdit(Dialog)
        self.EditDialog.setGeometry(QtCore.QRect(47, 9, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialog.setFont(font)
        self.EditDialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EditDialog.setReadOnly(True)
        self.EditDialog.setObjectName("EditDialog")
        self.labelDialog = QtWidgets.QLabel(Dialog)
        self.labelDialog.setGeometry(QtCore.QRect(10, 12, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelDialog.setFont(font)
        self.labelDialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDialog.setObjectName("labelDialog")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 67, 320, 215))
        self.tableWidget.setMinimumSize(QtCore.QSize(320, 215))
        self.tableWidget.setMaximumSize(QtCore.QSize(320, 215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(320, 185))
        self.tableWidget.setBaseSize(QtCore.QSize(320, 185))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(318)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(318)
        self.btItDel = QtWidgets.QPushButton(Dialog)
        self.btItDel.setGeometry(QtCore.QRect(270, 9, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btItDel.setFont(font)
        self.btItDel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btItDel.setText("")
        self.btItDel.setFlat(True)
        self.btItDel.setObjectName("btItDel")
        self.btItAdd = QtWidgets.QPushButton(Dialog)
        self.btItAdd.setGeometry(QtCore.QRect(245, 9, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btItAdd.setFont(font)
        self.btItAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btItAdd.setText("")
        self.btItAdd.setFlat(True)
        self.btItAdd.setObjectName("btItAdd")
        self.btItSave = QtWidgets.QPushButton(Dialog)
        self.btItSave.setGeometry(QtCore.QRect(298, 9, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btItSave.setFont(font)
        self.btItSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btItSave.setText("")
        self.btItSave.setFlat(True)
        self.btItSave.setObjectName("btItSave")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDialog.setText(_translate("Dialog", "Item"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Opzioni"))

