# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/dialogDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogDatabase(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 170)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(325, 170))
        Dialog.setSizeIncrement(QtCore.QSize(325, 170))
        Dialog.setBaseSize(QtCore.QSize(325, 170))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EditDialogHostname = QtWidgets.QLineEdit(Dialog)
        self.EditDialogHostname.setEnabled(True)
        self.EditDialogHostname.setGeometry(QtCore.QRect(95, 20, 170, 25))
        self.EditDialogHostname.setMinimumSize(QtCore.QSize(170, 25))
        self.EditDialogHostname.setMaximumSize(QtCore.QSize(170, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialogHostname.setFont(font)
        self.EditDialogHostname.setReadOnly(False)
        self.EditDialogHostname.setObjectName("EditDialogHostname")
        self.labelHost = QtWidgets.QLabel(Dialog)
        self.labelHost.setGeometry(QtCore.QRect(34, 23, 60, 20))
        self.labelHost.setMinimumSize(QtCore.QSize(50, 20))
        self.labelHost.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelHost.setFont(font)
        self.labelHost.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelHost.setObjectName("labelHost")
        self.btSave = QtWidgets.QPushButton(Dialog)
        self.btSave.setGeometry(QtCore.QRect(160, 140, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btSave.setFont(font)
        self.btSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSave.setText("")
        self.btSave.setFlat(True)
        self.btSave.setObjectName("btSave")
        self.EditDialogPwd = QtWidgets.QLineEdit(Dialog)
        self.EditDialogPwd.setEnabled(True)
        self.EditDialogPwd.setGeometry(QtCore.QRect(95, 106, 170, 25))
        self.EditDialogPwd.setMinimumSize(QtCore.QSize(170, 25))
        self.EditDialogPwd.setMaximumSize(QtCore.QSize(170, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialogPwd.setFont(font)
        self.EditDialogPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.EditDialogPwd.setReadOnly(False)
        self.EditDialogPwd.setObjectName("EditDialogPwd")
        self.labelPassword = QtWidgets.QLabel(Dialog)
        self.labelPassword.setGeometry(QtCore.QRect(31, 109, 65, 20))
        self.labelPassword.setMinimumSize(QtCore.QSize(65, 20))
        self.labelPassword.setMaximumSize(QtCore.QSize(65, 20))
        self.labelPassword.setBaseSize(QtCore.QSize(65, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelPassword.setObjectName("labelPassword")
        self.EditDialogDatabase = QtWidgets.QLineEdit(Dialog)
        self.EditDialogDatabase.setEnabled(True)
        self.EditDialogDatabase.setGeometry(QtCore.QRect(95, 47, 170, 25))
        self.EditDialogDatabase.setMinimumSize(QtCore.QSize(170, 25))
        self.EditDialogDatabase.setMaximumSize(QtCore.QSize(170, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialogDatabase.setFont(font)
        self.EditDialogDatabase.setReadOnly(False)
        self.EditDialogDatabase.setObjectName("EditDialogDatabase")
        self.labelDatabase = QtWidgets.QLabel(Dialog)
        self.labelDatabase.setGeometry(QtCore.QRect(33, 50, 60, 20))
        self.labelDatabase.setMinimumSize(QtCore.QSize(50, 20))
        self.labelDatabase.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelDatabase.setFont(font)
        self.labelDatabase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelDatabase.setObjectName("labelDatabase")
        self.EditDialogUsername = QtWidgets.QLineEdit(Dialog)
        self.EditDialogUsername.setEnabled(True)
        self.EditDialogUsername.setGeometry(QtCore.QRect(95, 77, 170, 25))
        self.EditDialogUsername.setMinimumSize(QtCore.QSize(170, 25))
        self.EditDialogUsername.setMaximumSize(QtCore.QSize(170, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.EditDialogUsername.setFont(font)
        self.EditDialogUsername.setReadOnly(False)
        self.EditDialogUsername.setObjectName("EditDialogUsername")
        self.labelUsername = QtWidgets.QLabel(Dialog)
        self.labelUsername.setGeometry(QtCore.QRect(47, 80, 60, 20))
        self.labelUsername.setMinimumSize(QtCore.QSize(50, 20))
        self.labelUsername.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelUsername.setObjectName("labelUsername")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EditDialogHostname, self.EditDialogDatabase)
        Dialog.setTabOrder(self.EditDialogDatabase, self.EditDialogUsername)
        Dialog.setTabOrder(self.EditDialogUsername, self.EditDialogPwd)
        Dialog.setTabOrder(self.EditDialogPwd, self.btSave)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelHost.setText(_translate("Dialog", "Hostname"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.labelDatabase.setText(_translate("Dialog", "Database"))
        self.labelUsername.setText(_translate("Dialog", "Utente"))

