# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1030, 700))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(54, 3, 971, 661))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = QtWidgets.QWidget()
        self.tab_main.setObjectName("tab_main")
        self.line_5 = QtWidgets.QFrame(self.tab_main)
        self.line_5.setGeometry(QtCore.QRect(567, 601, 260, 20))
        self.line_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.btPlus = QtWidgets.QPushButton(self.tab_main)
        self.btPlus.setGeometry(QtCore.QRect(278, 75, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btPlus.setFont(font)
        self.btPlus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btPlus.setText("")
        self.btPlus.setFlat(True)
        self.btPlus.setObjectName("btPlus")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_main)
        self.tableWidget.setGeometry(QtCore.QRect(1, 103, 555, 540))
        self.tableWidget.setMinimumSize(QtCore.QSize(555, 540))
        self.tableWidget.setMaximumSize(QtCore.QSize(555, 540))
        self.tableWidget.setBaseSize(QtCore.QSize(555, 540))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.labelLines = QtWidgets.QLabel(self.tab_main)
        self.labelLines.setGeometry(QtCore.QRect(1, 77, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelLines.setFont(font)
        self.labelLines.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelLines.setObjectName("labelLines")
        self.labelConnesso = QtWidgets.QLabel(self.tab_main)
        self.labelConnesso.setGeometry(QtCore.QRect(570, 610, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelConnesso.setFont(font)
        self.labelConnesso.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelConnesso.setObjectName("labelConnesso")
        self.line_2 = QtWidgets.QFrame(self.tab_main)
        self.line_2.setGeometry(QtCore.QRect(555, -13, 19, 651))
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btMinus = QtWidgets.QPushButton(self.tab_main)
        self.btMinus.setGeometry(QtCore.QRect(303, 75, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btMinus.setFont(font)
        self.btMinus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btMinus.setText("")
        self.btMinus.setFlat(True)
        self.btMinus.setObjectName("btMinus")
        self.labelLogo = QtWidgets.QLabel(self.tab_main)
        self.labelLogo.setGeometry(QtCore.QRect(841, 554, 130, 100))
        self.labelLogo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelLogo.setText("")
        self.labelLogo.setObjectName("labelLogo")
        self.labelUserName = QtWidgets.QLabel(self.tab_main)
        self.labelUserName.setGeometry(QtCore.QRect(691, 611, 130, 17))
        self.labelUserName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelUserName.setText("")
        self.labelUserName.setObjectName("labelUserName")
        self.line_4 = QtWidgets.QFrame(self.tab_main)
        self.line_4.setGeometry(QtCore.QRect(-13, -16, 19, 221))
        self.line_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.cbItem = QtWidgets.QComboBox(self.tab_main)
        self.cbItem.setGeometry(QtCore.QRect(331, 44, 179, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.cbItem.setFont(font)
        self.cbItem.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cbItem.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbItem.setDuplicatesEnabled(True)
        self.cbItem.setObjectName("cbItem")
        self.cbItem.addItem("")
        self.labelItems = QtWidgets.QLabel(self.tab_main)
        self.labelItems.setGeometry(QtCore.QRect(283, 46, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelItems.setFont(font)
        self.labelItems.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelItems.setObjectName("labelItems")
        self.labelHardware = QtWidgets.QLabel(self.tab_main)
        self.labelHardware.setGeometry(QtCore.QRect(262, 21, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelHardware.setFont(font)
        self.labelHardware.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelHardware.setObjectName("labelHardware")
        self.cbHardware = QtWidgets.QComboBox(self.tab_main)
        self.cbHardware.setGeometry(QtCore.QRect(331, 18, 179, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.cbHardware.setFont(font)
        self.cbHardware.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cbHardware.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbHardware.setDuplicatesEnabled(True)
        self.cbHardware.setObjectName("cbHardware")
        self.cbHardware.addItem("")
        self.labelFiltri = QtWidgets.QLabel(self.tab_main)
        self.labelFiltri.setGeometry(QtCore.QRect(330, -1, 50, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelFiltri.setFont(font)
        self.labelFiltri.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelFiltri.setObjectName("labelFiltri")
        self.btItemMinus = QtWidgets.QPushButton(self.tab_main)
        self.btItemMinus.setGeometry(QtCore.QRect(535, 45, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btItemMinus.setFont(font)
        self.btItemMinus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btItemMinus.setText("")
        self.btItemMinus.setFlat(True)
        self.btItemMinus.setObjectName("btItemMinus")
        self.btHwMinus = QtWidgets.QPushButton(self.tab_main)
        self.btHwMinus.setGeometry(QtCore.QRect(535, 17, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btHwMinus.setFont(font)
        self.btHwMinus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btHwMinus.setText("")
        self.btHwMinus.setFlat(True)
        self.btHwMinus.setObjectName("btHwMinus")
        self.btHwPlus = QtWidgets.QPushButton(self.tab_main)
        self.btHwPlus.setGeometry(QtCore.QRect(510, 17, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btHwPlus.setFont(font)
        self.btHwPlus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btHwPlus.setText("")
        self.btHwPlus.setFlat(True)
        self.btHwPlus.setObjectName("btHwPlus")
        self.btItemPlus = QtWidgets.QPushButton(self.tab_main)
        self.btItemPlus.setGeometry(QtCore.QRect(510, 45, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btItemPlus.setFont(font)
        self.btItemPlus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btItemPlus.setText("")
        self.btItemPlus.setFlat(True)
        self.btItemPlus.setObjectName("btItemPlus")
        self.btDownload = QtWidgets.QPushButton(self.tab_main)
        self.btDownload.setGeometry(QtCore.QRect(696, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btDownload.setFont(font)
        self.btDownload.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btDownload.setText("")
        self.btDownload.setFlat(True)
        self.btDownload.setObjectName("btDownload")
        self.btUpload = QtWidgets.QPushButton(self.tab_main)
        self.btUpload.setGeometry(QtCore.QRect(671, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btUpload.setFont(font)
        self.btUpload.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btUpload.setText("")
        self.btUpload.setFlat(True)
        self.btUpload.setObjectName("btUpload")
        self.tableWidget_attachments = QtWidgets.QTableWidget(self.tab_main)
        self.tableWidget_attachments.setGeometry(QtCore.QRect(570, 26, 391, 101))
        self.tableWidget_attachments.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_attachments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_attachments.setDragDropOverwriteMode(False)
        self.tableWidget_attachments.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_attachments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_attachments.setObjectName("tableWidget_attachments")
        self.tableWidget_attachments.setColumnCount(1)
        self.tableWidget_attachments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget_attachments.setHorizontalHeaderItem(0, item)
        self.labelAttach = QtWidgets.QLabel(self.tab_main)
        self.labelAttach.setGeometry(QtCore.QRect(570, 0, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAttach.setFont(font)
        self.labelAttach.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelAttach.setObjectName("labelAttach")
        self.btTrash = QtWidgets.QPushButton(self.tab_main)
        self.btTrash.setGeometry(QtCore.QRect(888, -2, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btTrash.setFont(font)
        self.btTrash.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btTrash.setText("")
        self.btTrash.setFlat(True)
        self.btTrash.setObjectName("btTrash")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_main)
        self.plainTextEdit.setGeometry(QtCore.QRect(570, 134, 391, 421))
        self.plainTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.line = QtWidgets.QFrame(self.tab_main)
        self.line.setGeometry(QtCore.QRect(-1, 68, 560, 16))
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.tab_main)
        self.line_3.setGeometry(QtCore.QRect(243, -3, 19, 81))
        self.line_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btSave = QtWidgets.QPushButton(self.tab_main)
        self.btSave.setGeometry(QtCore.QRect(570, 585, 39, 25))
        self.btSave.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btSave.setToolTip("")
        self.btSave.setStatusTip("")
        self.btSave.setWhatsThis("")
        self.btSave.setAccessibleName("")
        self.btSave.setAccessibleDescription("")
        self.btSave.setText("")
        self.btSave.setFlat(False)
        self.btSave.setProperty("toolTipDuration", 10)
        self.btSave.setObjectName("btSave")
        self.labelupdate = QtWidgets.QLabel(self.tab_main)
        self.labelupdate.setGeometry(QtCore.QRect(611, 587, 171, 19))
        self.labelupdate.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelupdate.setObjectName("labelupdate")
        self.btModify = QtWidgets.QPushButton(self.tab_main)
        self.btModify.setGeometry(QtCore.QRect(570, 559, 39, 25))
        self.btModify.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btModify.setToolTip("")
        self.btModify.setStatusTip("")
        self.btModify.setWhatsThis("")
        self.btModify.setAccessibleName("")
        self.btModify.setAccessibleDescription("")
        self.btModify.setText("")
        self.btModify.setFlat(False)
        self.btModify.setProperty("toolTipDuration", 10)
        self.btModify.setObjectName("btModify")
        self.labelallowmodify = QtWidgets.QLabel(self.tab_main)
        self.labelallowmodify.setGeometry(QtCore.QRect(611, 561, 141, 19))
        self.labelallowmodify.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelallowmodify.setObjectName("labelallowmodify")
        self.labelDeleteFile = QtWidgets.QLabel(self.tab_main)
        self.labelDeleteFile.setGeometry(QtCore.QRect(780, 0, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDeleteFile.setFont(font)
        self.labelDeleteFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelDeleteFile.setObjectName("labelDeleteFile")
        self.line_5.raise_()
        self.btPlus.raise_()
        self.tableWidget.raise_()
        self.labelLines.raise_()
        self.labelConnesso.raise_()
        self.line_2.raise_()
        self.btMinus.raise_()
        self.labelLogo.raise_()
        self.labelUserName.raise_()
        self.line_4.raise_()
        self.labelHardware.raise_()
        self.cbItem.raise_()
        self.cbHardware.raise_()
        self.labelItems.raise_()
        self.labelFiltri.raise_()
        self.btItemMinus.raise_()
        self.btHwMinus.raise_()
        self.btHwPlus.raise_()
        self.btItemPlus.raise_()
        self.btDownload.raise_()
        self.btUpload.raise_()
        self.tableWidget_attachments.raise_()
        self.labelAttach.raise_()
        self.btTrash.raise_()
        self.plainTextEdit.raise_()
        self.line.raise_()
        self.line_3.raise_()
        self.btSave.raise_()
        self.labelupdate.raise_()
        self.btModify.raise_()
        self.labelallowmodify.raise_()
        self.labelDeleteFile.raise_()
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_attachments = QtWidgets.QWidget()
        self.tab_attachments.setObjectName("tab_attachments")
        self.labelFoto = QtWidgets.QLabel(self.tab_attachments)
        self.labelFoto.setGeometry(QtCore.QRect(260, 50, 700, 550))
        self.labelFoto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelFoto.setText("")
        self.labelFoto.setObjectName("labelFoto")
        self.btPlus_foto = QtWidgets.QToolButton(self.tab_attachments)
        self.btPlus_foto.setGeometry(QtCore.QRect(7, 50, 90, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.btPlus_foto.setFont(font)
        self.btPlus_foto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btPlus_foto.setText("")
        self.btPlus_foto.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btPlus_foto.setObjectName("btPlus_foto")
        self.tableWidgetImg = QtWidgets.QTableWidget(self.tab_attachments)
        self.tableWidgetImg.setGeometry(QtCore.QRect(0, 90, 250, 530))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(55)
        sizePolicy.setHeightForWidth(self.tableWidgetImg.sizePolicy().hasHeightForWidth())
        self.tableWidgetImg.setSizePolicy(sizePolicy)
        self.tableWidgetImg.setMinimumSize(QtCore.QSize(250, 530))
        self.tableWidgetImg.setMaximumSize(QtCore.QSize(250, 530))
        self.tableWidgetImg.setSizeIncrement(QtCore.QSize(250, 530))
        self.tableWidgetImg.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.tableWidgetImg.setFont(font)
        self.tableWidgetImg.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidgetImg.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetImg.setTabKeyNavigation(False)
        self.tableWidgetImg.setProperty("showDropIndicator", False)
        self.tableWidgetImg.setDragDropOverwriteMode(False)
        self.tableWidgetImg.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetImg.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetImg.setObjectName("tableWidgetImg")
        self.tableWidgetImg.setColumnCount(1)
        self.tableWidgetImg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImg.setHorizontalHeaderItem(0, item)
        self.tableWidgetImg.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidgetImg.horizontalHeader().setMinimumSectionSize(250)
        self.btMinus_foto = QtWidgets.QToolButton(self.tab_attachments)
        self.btMinus_foto.setGeometry(QtCore.QRect(130, 50, 90, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.btMinus_foto.setFont(font)
        self.btMinus_foto.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btMinus_foto.setText("")
        self.btMinus_foto.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btMinus_foto.setObjectName("btMinus_foto")
        self.btPlus_foto.raise_()
        self.tableWidgetImg.raise_()
        self.btMinus_foto.raise_()
        self.labelFoto.raise_()
        self.tabWidget.addTab(self.tab_attachments, "")
        self.btLogout = QtWidgets.QPushButton(self.centralWidget)
        self.btLogout.setGeometry(QtCore.QRect(10, 63, 39, 25))
        self.btLogout.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btLogout.setToolTip("")
        self.btLogout.setStatusTip("")
        self.btLogout.setWhatsThis("")
        self.btLogout.setAccessibleName("")
        self.btLogout.setAccessibleDescription("")
        self.btLogout.setText("")
        self.btLogout.setFlat(False)
        self.btLogout.setProperty("toolTipDuration", 10)
        self.btLogout.setObjectName("btLogout")
        self.btPDF = QtWidgets.QPushButton(self.centralWidget)
        self.btPDF.setGeometry(QtCore.QRect(10, 142, 39, 25))
        self.btPDF.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btPDF.setToolTip("")
        self.btPDF.setStatusTip("")
        self.btPDF.setWhatsThis("")
        self.btPDF.setAccessibleName("")
        self.btPDF.setAccessibleDescription("")
        self.btPDF.setText("")
        self.btPDF.setFlat(False)
        self.btPDF.setProperty("toolTipDuration", 10)
        self.btPDF.setObjectName("btPDF")
        self.btPassword = QtWidgets.QPushButton(self.centralWidget)
        self.btPassword.setGeometry(QtCore.QRect(10, 36, 39, 25))
        self.btPassword.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btPassword.setToolTip("")
        self.btPassword.setStatusTip("")
        self.btPassword.setWhatsThis("")
        self.btPassword.setAccessibleName("")
        self.btPassword.setAccessibleDescription("")
        self.btPassword.setText("")
        self.btPassword.setFlat(False)
        self.btPassword.setProperty("toolTipDuration", 10)
        self.btPassword.setObjectName("btPassword")
        self.btLogs = QtWidgets.QPushButton(self.centralWidget)
        self.btLogs.setGeometry(QtCore.QRect(10, 116, 39, 25))
        self.btLogs.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btLogs.setToolTip("")
        self.btLogs.setStatusTip("")
        self.btLogs.setWhatsThis("")
        self.btLogs.setAccessibleName("")
        self.btLogs.setAccessibleDescription("")
        self.btLogs.setText("")
        self.btLogs.setFlat(False)
        self.btLogs.setProperty("toolTipDuration", 10)
        self.btLogs.setObjectName("btLogs")
        self.btLogin = QtWidgets.QPushButton(self.centralWidget)
        self.btLogin.setGeometry(QtCore.QRect(10, 10, 39, 25))
        self.btLogin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btLogin.setToolTip("")
        self.btLogin.setStatusTip("")
        self.btLogin.setWhatsThis("")
        self.btLogin.setAccessibleName("")
        self.btLogin.setAccessibleDescription("")
        self.btLogin.setText("")
        self.btLogin.setFlat(False)
        self.btLogin.setProperty("toolTipDuration", 10)
        self.btLogin.setObjectName("btLogin")
        self.btUsers = QtWidgets.QPushButton(self.centralWidget)
        self.btUsers.setGeometry(QtCore.QRect(10, 90, 39, 25))
        self.btUsers.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btUsers.setToolTip("")
        self.btUsers.setStatusTip("")
        self.btUsers.setWhatsThis("")
        self.btUsers.setAccessibleName("")
        self.btUsers.setAccessibleDescription("")
        self.btUsers.setText("")
        self.btUsers.setFlat(False)
        self.btUsers.setProperty("toolTipDuration", 10)
        self.btUsers.setObjectName("btUsers")
        self.cbClient = QtWidgets.QComboBox(self.centralWidget)
        self.cbClient.setGeometry(QtCore.QRect(57, 49, 179, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.cbClient.setFont(font)
        self.cbClient.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cbClient.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cbClient.setDuplicatesEnabled(True)
        self.cbClient.setObjectName("cbClient")
        self.cbClient.addItem("")
        self.btClientPlus = QtWidgets.QPushButton(self.centralWidget)
        self.btClientPlus.setGeometry(QtCore.QRect(242, 50, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btClientPlus.setFont(font)
        self.btClientPlus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btClientPlus.setText("")
        self.btClientPlus.setFlat(True)
        self.btClientPlus.setObjectName("btClientPlus")
        self.btClientMinus = QtWidgets.QPushButton(self.centralWidget)
        self.btClientMinus.setGeometry(QtCore.QRect(267, 50, 24, 25))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.btClientMinus.setFont(font)
        self.btClientMinus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btClientMinus.setText("")
        self.btClientMinus.setFlat(True)
        self.btClientMinus.setObjectName("btClientMinus")
        self.labelCliente = QtWidgets.QLabel(self.centralWidget)
        self.labelCliente.setGeometry(QtCore.QRect(59, 31, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCliente.setFont(font)
        self.labelCliente.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelCliente.setObjectName("labelCliente")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 30, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.statusBar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShowClients = QtWidgets.QAction(MainWindow)
        self.actionShowClients.setObjectName("actionShowClients")
        self.actionAddClient = QtWidgets.QAction(MainWindow)
        self.actionAddClient.setObjectName("actionAddClient")
        self.actionFindClient = QtWidgets.QAction(MainWindow)
        self.actionFindClient.setObjectName("actionFindClient")
        self.actionModClient = QtWidgets.QAction(MainWindow)
        self.actionModClient.setObjectName("actionModClient")
        self.actionDeleteClient = QtWidgets.QAction(MainWindow)
        self.actionDeleteClient.setObjectName("actionDeleteClient")
        self.actionNewHw = QtWidgets.QAction(MainWindow)
        self.actionNewHw.setObjectName("actionNewHw")
        self.actionNewItem = QtWidgets.QAction(MainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionDeleteHw = QtWidgets.QAction(MainWindow)
        self.actionDeleteHw.setObjectName("actionDeleteHw")
        self.actionDeleteItem = QtWidgets.QAction(MainWindow)
        self.actionDeleteItem.setObjectName("actionDeleteItem")
        self.actionEsporta_in_PDF = QtWidgets.QAction(MainWindow)
        self.actionEsporta_in_PDF.setObjectName("actionEsporta_in_PDF")
        self.actionChangePassword = QtWidgets.QAction(MainWindow)
        self.actionChangePassword.setObjectName("actionChangePassword")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aron Config"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hardware"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Campo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Value"))
        self.labelLines.setText(_translate("MainWindow", "Configurazioni da accordo ai filtri"))
        self.labelConnesso.setText(_translate("MainWindow", "Connesso come:"))
        self.cbItem.setItemText(0, _translate("MainWindow", "Seleziona"))
        self.labelItems.setText(_translate("MainWindow", "Campo"))
        self.labelHardware.setText(_translate("MainWindow", "Hardware"))
        self.cbHardware.setProperty("currentText", _translate("MainWindow", "Seleziona"))
        self.cbHardware.setItemText(0, _translate("MainWindow", "Seleziona"))
        self.labelFiltri.setText(_translate("MainWindow", "Filtri"))
        item = self.tableWidget_attachments.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome File"))
        self.labelAttach.setText(_translate("MainWindow", "Opzioni File"))
        self.labelupdate.setText(_translate("MainWindow", "Aggiorna cambiamenti"))
        self.labelallowmodify.setText(_translate("MainWindow", "Abilita modifica"))
        self.labelDeleteFile.setText(_translate("MainWindow", "Cancella File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("MainWindow", "Principale"))
        item = self.tableWidgetImg.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Immagini"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_attachments), _translate("MainWindow", "Galleria Immagine"))
        self.cbClient.setItemText(0, _translate("MainWindow", "Seleziona"))
        self.labelCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))
        self.actionShowClients.setText(_translate("MainWindow", "Visualizza Tutti"))
        self.actionAddClient.setText(_translate("MainWindow", "Aggiungi"))
        self.actionFindClient.setText(_translate("MainWindow", "Cerca"))
        self.actionModClient.setText(_translate("MainWindow", "Modifica"))
        self.actionDeleteClient.setText(_translate("MainWindow", "Cancella"))
        self.actionNewHw.setText(_translate("MainWindow", "Nuovo Hardware"))
        self.actionNewItem.setText(_translate("MainWindow", "Nuovo Campo"))
        self.actionDeleteHw.setText(_translate("MainWindow", "Hardware"))
        self.actionDeleteItem.setText(_translate("MainWindow", "Campo"))
        self.actionEsporta_in_PDF.setText(_translate("MainWindow", "Esporta in PDF"))
        self.actionChangePassword.setText(_translate("MainWindow", "Cambia Password"))

